/*
   Find the Difference:
   
   You are given two strings s and t.
   
   String t is generated by random shuffling string s and then add one more letter at a random position.
   
   Return the letter that was added to t.
   
   Problem Source: https://leetcode.com/problems/find-the-difference/
   
   ----
   
   Algorithm:
   
   1. Create a count table, int[] count = new int[26], for 25 alphabets.
   2. loop through string s, increment the count index
   3. Loop through string t, decrement the count index
   4. If any of the index is -1, return the char value of the decimal value ('a' + i), for that index.
   5. Otherwise, return empty char.
   
   -----
   
   Time-Complexity: O(N+M), where N is the number of chars in String s, M is the number of chars in String t.
   Space-Complexity: O(1), this solution takes constant space.

*/

class FindTheDifference
{
   public static void main(String[] args)
   {
      
      String s1 = "abcd";
      String t1 = "abcde";
      
      String s2 = "";
      String t2 = "y";
      
      String s3 = "ae";
      String t3 = "aea";
      
      System.out.println(findTheDifference(s3, t3));
   }
   
   public static char findTheDifference(String s, String t)
   {
      int[] count = new int[26];
      
      for(int i=0; i < s.length(); i++)
      {
         int index = s.charAt(i) - 'a';
         
         count[index]++;
      }
      
      for(int i=0; i < t.length(); i++)
      {
         int index = t.charAt(i) - 'a';
         
         count[index]--;
      }
      
      for(int i=0; i < count.length; i++)
      {
         if(count[i] < 0)
         {
            return (char)('a' + i);
         }
      }
      
      return ' ';

   }
}